# Generated by Django 5.0.7 on 2024-09-13 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_classif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='classif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classif'),
        ),
    ]
